import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import findCacheDir from "find-cache-dir";
import * as fs from "fs";
import * as path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

let combineCssPlugin = {
  name: "combine-css",
  setup(build) {
    build.onEnd((result) => {
      try {
        const customStyles = fs.readFileSync("plugin.css", "utf8");
        const monacoStyles = fs.readFileSync("main.css", "utf8");
        const combined = customStyles + "\n" + monacoStyles;
        fs.writeFileSync("styles.css", combined, "utf8");
      } catch (e) {
        console.warn("CSS combination failed:", e.message);
      }
    });
  },
};

let inlineWorkerPlugin = {
  name: "inline-worker-plugin",
  setup(build) {
    build.onLoad(
      { filter: /\.(service|worker).(js|jsx|ts|tsx)$/ },
      async ({ path: workerPath }) => {
        let workerCode = await buildWorker(workerPath);
        return {
          contents: `
                export default function inlineWorker() {
                    let blob = new Blob([${JSON.stringify(workerCode)}])
                    let url = URL.createObjectURL(blob)
                    let worker = ${
                      workerPath.includes("service")
                        ? "navigator.serviceWorker.register(url, {scope: '/'})"
                        : "new Worker(url)"
                    };
                    URL.revokeObjectURL(url)
                    return worker
                }`,
          loader: "js",
        };
      }
    );
  },
};

let wasmPlugin = {
  name: "wasm",
  setup(build) {
    // Resolve ".wasm" files to a path with a namespace
    build.onResolve({ filter: /\.wasm$/ }, (args) => {
      if (args.resolveDir === "") {
        return; // Ignore unresolvable paths
      }
      return {
        path: path.isAbsolute(args.path)
          ? args.path
          : path.join(args.resolveDir, args.path),
        namespace: "wasm-binary",
      };
    });
    // Virtual modules in the "wasm-binary" namespace contain the
    // actual bytes of the WebAssembly file. This uses esbuild's
    // built-in "binary" loader instead of manually embedding the
    // binary data inside JavaScript code ourselves.
    build.onLoad({ filter: /.*/, namespace: "wasm-binary" }, async (args) => ({
      contents: await fs.promises.readFile(args.path),
      loader: "binary",
    }));
  },
};

let cacheDir = findCacheDir({
  name: "inline-sevice-worker",
  create: true,
});

async function buildWorker(workerPath) {
  let scriptNameParts = path.basename(workerPath).split(".");
  scriptNameParts.pop();
  scriptNameParts.push("js");
  let scriptName = scriptNameParts.join(".");
  let bundlePath = path.resolve(cacheDir, scriptName);

  await esbuild.build({
    entryPoints: [workerPath],
    bundle: true,
    minify: true,
    outfile: bundlePath,
    target: "es2018",
    format: "cjs",
    // The wasm-bindgen glue (pkg/) references `import.meta.url` only in an
    // unused fallback branch (the worker always passes the wasm explicitly).
    // Define it so the es2018 target doesn't emit an empty-import-meta warning.
    define: {
      "import.meta.url": '""',
    },
  });

  return fs.promises.readFile(bundlePath, { encoding: "utf-8" });
}

// Redirect the bare "monaco-editor" import in the main bundle to a tiny shim so
// monaco (~9 MB) is NOT bundled into main.js. Subpath imports (e.g. the CSS at
// "monaco-editor/min/...") are left untouched and resolve to the real package.
let monacoShimPlugin = {
  name: "monaco-shim",
  setup(build) {
    build.onResolve({ filter: /^monaco-editor$/ }, () => ({
      path: path.resolve("src/monacoExternal.cjs"),
    }));
  },
};

// Build monaco into its own desktop-only file (monaco.js). It is loaded at
// runtime only on desktop (see TypstForObsidian.loadMonaco), keeping main.js
// small enough to sync to mobile via Obsidian Sync (5 MB per-file limit).
async function buildMonaco() {
  await esbuild.build({
    entryPoints: ["src/monacoBundle.ts"],
    bundle: true,
    minify: true,
    format: "iife",
    target: "es2018",
    logLevel: "info",
    outfile: "monaco.js",
    // monaco's CSS is already shipped in styles.css via main.ts's explicit
    // `editor.main.css` import, so drop CSS here to avoid a duplicate file.
    loader: { ".css": "empty", ".ttf": "base64" },
    logOverride: { "css-syntax-error": "silent" },
  });
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "pdfjs-dist/build/pdf.worker.min.mjs",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "images/*.svg",
    "images/*.gif",
    ...builtins,
  ],
  loader: {
    ".svg": "empty",
    ".gif": "empty",
    ".ttf": "base64",
  },
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // monaco-editor ships nested CSS (e.g. `a { ... }`) that esbuild flags as
  // ambiguous but rewrites correctly to `:is(a)`. Silence this vendor-only
  // warning rather than patching node_modules.
  logOverride: {
    "css-syntax-error": "silent",
  },
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    PLUGIN_VERSION: JSON.stringify(process.env.npm_package_version),
  },
  plugins: [monacoShimPlugin, inlineWorkerPlugin, wasmPlugin, combineCssPlugin],
});

// monaco.js rarely changes and is slow to build, so build it once up front
// rather than on every watch rebuild.
await buildMonaco();

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
